(function() {

  $(function() {
    var Bundesland, Land;
    Land = (function() {

      function Land() {
        this.bundeslaender = [];
      }

      return Land;

    })();
    Bundesland = (function() {

      function Bundesland(name, land) {
        this.name = name;
        this.land = land;
        this.einwohner = 0;
        this.dichte = 0;
        this.verletzte = 0;
        this.pro_tausend = 0;
      }

      Bundesland.prototype.verletzte_pro_tausend = function() {
        return this.pro_tausend = (100000 * this.verletzte) / this.einwohner;
      };

      Bundesland.prototype.verletzte_text = function() {
        return d3.round(this.pro_tausend) + " Verletze pro 100.000 Einwohner";
      };

      return Bundesland;

    })();
    return d3.json("/fahrrad/data/fahrradunfalle_deutschland.json", function(data) {
      var deutschland, domain_range, quantize;
      deutschland = new Land();
      domain_range = [];
      data.forEach(function(bundesland) {
        var land;
        land = new Bundesland(bundesland.bundesland, deutschland);
        land.einwohner = bundesland.einwohner;
        land.verletzte = bundesland.verletze;
        land.dichte = bundesland.dichte;
        land.verletzte_pro_tausend();
        domain_range.push(land.pro_tausend);
        return deutschland.bundeslaender.push(land);
      });
      quantize = d3.scale.quantile().domain(domain_range).range(d3.range(9));
      return deutschland.bundeslaender.forEach(function(bundesland) {
        return d3.select('#' + bundesland.name).attr('class', function(d, i) {
          return 'q' + quantize(bundesland.pro_tausend) + '-9';
        }).append("svg:title").text(function(d) {
          return bundesland.verletzte_text();
        });
      });
    });
  });

}).call(this);

// Generated by CoffeeScript 1.5.0-pre
